In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets as ds
import tensorflow as tf
import seaborn as sns

In [67]:
x_val = [
    [3.0, 2.0],
    [1.0, 2.0],
]

In [95]:
# x = tf.placeholder(tf.float32, [None, 2], name='x')
y = tf.placeholder(tf.float32, [None, 1], name='y')

z1, z2 = tf.split(x, [1, 1], axis=1)

y = x

k = 1
for i in range(2, 3):
    for j in range(i+1):
        print ("{2} : x1^{0} * x2^{1}".format(i-j, j, k))
        k = k + 1
        a = pow(z1, i-j) * pow(z2, j)
        print(a.shape)
        y = tf.concat([y, a], axis=1)

with tf.Session() as sess:
    y_val = sess.run(y, {x: x_val})
    z1_val, z2_val = sess.run((z1, z2), {x: x_val})
    print(y_val)
    print(z1_val)
    print(z2_val)

1 : x1^2 * x2^0
(?, 1)
2 : x1^1 * x2^1
(?, 1)
3 : x1^0 * x2^2
(?, 1)
[[3. 2. 9. 6. 4.]
 [1. 2. 1. 2. 4.]]
[[3.]
 [1.]]
[[2.]
 [2.]]
